language: node_js
node_js:
  - "6"
services:
  - postgresql
env:
- DATABASE_URL=postgres://localhost:5432/courtbot
before_script:
  - psql -c 'create database courtbot;' -U postgres
  - cp .env.sample .env
  - npm run dbsetup
addons:
  postgresql: "9.4"